sudo: required
dist: trusty

language: generic

env:
  global:
  - MAKEFLAGS=-j2

matrix:
  include:
  - os: linux
    env:
    - LABEL="ubuntu64"
    - APT_REPOS="ppa:ubuntu-toolchain-r/test"
    - APT_PACKAGES="gcc-4.9 g++-4.9 libdwarf-dev qtbase5-dev qtdeclarative5-dev"
    - CMAKE_OPTIONS="-DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9"
  - os: linux
    env:
    - LABEL="ubuntu64-clang"
    - APT_PACKAGES="clang-3.6 libc++-dev libc++abi-dev libdwarf-dev qtbase5-dev qtdeclarative5-dev"
    - CMAKE_OPTIONS="-DCMAKE_C_COMPILER=clang-3.6 -DCMAKE_CXX_COMPILER=clang++-3.6 -DCMAKE_CXX_FLAGS=-stdlib=libc++"
  - os: osx
    env:
    - LABEL="mac64"
    - CMAKE_OPTIONS=""

before_install:
- |
    if [ "$APT_PACKAGES" ]
      then for APT_REPO in $APT_REPOS
      do
        sudo add-apt-repository -y $APT_REPO
      done
      if [ "$CXX" == "clang++" ]
      then
        wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository -y 'deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.6 main'
      fi
      sudo apt-get update -qq
      sudo apt-get install -qq -y $APT_PACKAGES
    fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install qt5; export CMAKE_PREFIX_PATH=$(brew --prefix qt5); fi
- cmake --version

script:
- cmake -H. -Bbuild $CMAKE_OPTIONS
- cmake --build build --use-stderr -- -k
- build/bin/tests
